---
title: "wahlprogramme"
output: html_notebook
---

```{r}
packages <- c("dplyr", "magrittr", "quanteda", "stm", "manifestoR")

# install if necessary
install.packages(setdiff(packages, rownames(installed.packages())))  


# load
lapply(packages, library, character.only = TRUE)

```

```{r}
mp_setapikey("C:/Users/Jacob/OneDrive/uni/MA WiSoz/Semester III/Computational Social Sciences/foPra/API Keys/RManifesto.txt")

```

```{r}
my_corpus <- mp_corpus(countryname == "Germany" & edate > as.Date("2000-01-01"))

```

```{r}
cdu <- 41521
fdp <- 41420
spd <- 41320
greens1 <- 41111
greens2 <- 41112
greens3 <- 41113
pds <- 41221
pds_left <- 41222
left <- 41223
afd <- 41953
```


```{r}
parties <- c(cdu, fdp, spd, greens1, greens2, greens3, pds, pds_left, left, afd)
```



```{r}
germany_manifestos <- setNames(lapply(parties, function(p) mp_corpus(party == p)), parties)

```

```{r}
germany_manifestos_df <- setNames(lapply(parties, function(p) mp_corpus_df(party == p)), parties)

```


```{r}
# Merge the selected data frames and update "41111"
germany_manifestos_df[["41111"]] <- do.call(rbind, germany_manifestos_df[c("41111", "41112", "41113")])

germany_manifestos_df[["41221"]] <- do.call(rbind, germany_manifestos_df[c("41221", "41222", "41223")])

# Remove "41112" and "41113" in one step
germany_manifestos_df[c("41112", "41113")] <- NULL

germany_manifestos_df[c("41222", "41223")] <- NULL


```


```{r}
# Define new names
new_names <- c("CDU", "FDP", "SPD", "GREENS", "LEFT", "AFD")

# Assign new names to the list
names(germany_manifestos_df) <- new_names

```


```{r}
# Initialize an empty data frame
df_manifesto <- data.frame()

# Loop through the parties
for (p in new_names) {
  # Read the CSV file for the current party
  party_mani <- germany_manifestos_df[[p]]
  
  # Add a new column for the party name
  party_mani$party <- p
  
  # Concatenate the new data frame with the existing one
  df_manifesto <- rbind(df_manifesto, party_mani)
}

```

```{r}


# Convert the 'date' column to Date format (assuming 'date' is in YYYYMM format)
df_manifesto$date <- as.Date(paste0(df_manifesto$date, "01"), format = "%Y%m%d")

# Extract only the year from the 'date' column
df_manifesto$year <- format(df_manifesto$date, "%Y")

# Drop the specified columns
columns_to_drop <- c("eu_code", "pos", "language", "annotations", "translation_en", "year")
df_manifesto_final <- df_manifesto[, !(names(df_manifesto) %in% columns_to_drop)]


```


```{r}
corpus <- corpus(as.character(df_manifesto_final$text))

toks <- tokens(corpus, remove_punct = F,
               remove_numbers = T,
               remove_symbols = T,
               remove_separators = F,
               split_hyphens = F,
               remove_url = T,
               include_docvars = F)

toks <- tokens_wordstem(toks)
```

```{r}
# Convert tokens to a list of strings
tokens_list <- sapply(toks, function(x) paste(x, collapse = " "))

# Add the tokens as a new column in the DataFrame
df_manifesto_final$text_wordstem <- tokens_list
```


```{r}


write.csv(df_manifesto_final, file = "data/parties/All_Manifestos.csv", row.names = FALSE, fileEncoding = "UTF-8")  # Save as CSV

```



