---
title: "wahlprogramme"
output: html_notebook
---

```{r}
packages <- c(
  "dplyr", 
  "magrittr", 
  "quanteda", 
  #"stm", 
  "manifestoR"
  )

# install if necessary
install.packages(setdiff(packages, rownames(installed.packages())))  


# load
lapply(packages, library, character.only = TRUE)

```

Set the API key

```{r}
mp_setapikey("C:/Users/Jacob/OneDrive/uni/MA WiSoz/Semester III/Computational Social Sciences/foPra/API Keys/RManifesto.txt")

```

```{r}

# Define the party identifiers

cdu <- 41521
fdp <- 41420
spd <- 41320
greens1 <- 41111
greens2 <- 41112
greens3 <- 41113
pds <- 41221
pds_left <- 41222
left <- 41223
afd <- 41953
oevp <- 42520
spoe <- 42320
oe_gruene <- 42110
fpoe <- 42420
neos <- 42430

```

```{r}

# Create a list of the party IDs

parties_de <- c(cdu, fdp, spd, greens1, greens2, greens3, pds, pds_left, left, afd)

parties_oe <- c(oevp, spoe, oe_gruene, fpoe, neos)


```

```{r}

# Create a function to get the manifesto data for a party
germany_manifestos_df <- setNames(lapply(parties_de, function(p) mp_corpus_df(party == p)), parties_de)

austria_manifestos_df <- setNames(lapply(parties_oe, function(p) mp_corpus_df(party == p)), parties_oe)

```

```{r}
# Merge the selected data frames and update "41111"
germany_manifestos_df[["41111"]] <- do.call(rbind, germany_manifestos_df[c("41111", "41112", "41113")])

# Remove "41112" and "41113" in one step
germany_manifestos_df[["41221"]] <- do.call(rbind, germany_manifestos_df[c("41221", "41222", "41223")])

# Remove "41112" and "41113" in one step
germany_manifestos_df[c("41112", "41113")] <- NULL

# Remove "41222" and "41223" in one step
germany_manifestos_df[c("41222", "41223")] <- NULL


```

```{r}
# Define new names
new_names_de  <- c("CDU", "FDP", "SPD", "Greens DE", "Left", "AfD")
new_names_oe  <- c("ÖVP", "SPÖ", "Greens AU", "FPÖ", "Neos")

# Assign new names to the list
names(germany_manifestos_df) <- new_names_de
names(austria_manifestos_df) <- new_names_oe
```

```{r}
# Initialize an empty data frame
df_manifesto_de <- data.frame()
df_manifesto_oe <- data.frame()

# Loop through the parties
for (p in new_names_de) {
  # Read the CSV file for the current party
  party_mani <- germany_manifestos_df[[p]]
  
  # Add a new column for the party name
  party_mani$party <- p
  
  # Concatenate the new data frame with the existing one
  df_manifesto_de <- rbind(df_manifesto_de, party_mani)
}

df_manifesto_de$country <- "DE"

for (p in new_names_oe) {
  # Read the CSV file for the current party
  party_mani <- austria_manifestos_df[[p]]
  
  # Add a new column for the party name
  party_mani$party <- p
  
  # Concatenate the new data frame with the existing one
  df_manifesto_oe <- rbind(df_manifesto_oe, party_mani)
}

df_manifesto_oe$country <- "AU"

# Merge the data frames 

df_manifesto <- rbind(df_manifesto_de, df_manifesto_oe)

```

```{r}


# Convert the 'date' column to Date format (assuming 'date' is in YYYYMM format)
df_manifesto$date <- as.Date(paste0(df_manifesto$date, "01"), format = "%Y%m%d")

# Extract only the year from the 'date' column
df_manifesto$date <- format(df_manifesto$date, "%Y")

df_manifesto$year <- as.numeric(df_manifesto$date)

# Drop the specified columns
columns_to_drop <- c("eu_code", "pos", "language", "annotations", "translation_en", "date")
df_manifesto_final <- df_manifesto[, !(names(df_manifesto) %in% columns_to_drop)]


```

```{r}
# Create a corpus object
corpus <- corpus(as.character(df_manifesto_final$text))

# Tokenize the corpus
toks <- tokens(corpus, remove_punct = F,
               remove_numbers = F,
               remove_symbols = T,
               remove_separators = F,
               split_hyphens = F,
               remove_url = T,
               include_docvars = F)

# wordstem the tokens
# toks <- tokens_wordstem(toks)
```

```{r}
# Convert tokens to a list of strings
tokens_list <- sapply(toks, function(x) paste(x, collapse = ""))

# Add the tokens as a new column in the DataFrame

df_manifesto_toks <- df_manifesto_final
df_manifesto_toks$text <- tokens_list
```

```{r}
# Save the data frames as CSV files
write.csv(df_manifesto_final, file = "data/parties/All_Manifestos.csv", row.names = FALSE, fileEncoding = "UTF-8")  # Save as CSV

# write.csv(df_manifesto_toks, file = "data/parties/All_Manifestos_tokenized.csv", row.names = FALSE, fileEncoding = "UTF-8")  # Save as CSV

```
